#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/common/pywrap", sys.argv)

# Run this with --help to see available options for tracing and debugging
# See https://github.com/cockpit-project/cockpit/blob/main/test/common/testlib.py
# "class Browser" and "class MachineCase" for the available API.

import testlib


# Nondestructive tests all run in the same running VM. This allows them to run in Packit, Fedora, and
# RHEL dist-git gating. They must not permanently change any file or configuration on the system in a
# way that influences other tests.
@testlib.nondestructive
class TestApplication(testlib.MachineCase):
    def testBasic(self):
        b = self.browser

        self.login_and_go("/cockpit-docker")

        # both main listing cards are shown
        b.wait_in_text("#containers-containers .pf-v6-c-card__title", "Containers")
        b.wait_in_text("#containers-images .pf-v6-c-card__title", "Images")

        # no containers have been created yet
        b.wait_in_text("#containers-containers .pf-v6-c-empty-state", "No containers")

        # the image listing is collapsed by default; expand it
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        # the busybox image is pre-pulled into the test VM
        b.wait_in_text("#containers-images .image-name", "busybox")

    def testContainers(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        b.wait_in_text("#containers-images .image-name", "busybox")

        try:
            # start a container on the machine; it should show up in the UI
            m.execute("docker run -d --name test-cockpit-docker busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_in_text(".container-name", "test-cockpit-docker")
            b.wait_visible("tr[data-row-name='0-test-cockpit-docker']")
        finally:
            # clean up so the shared machine stays in a pristine state
            m.execute("docker rm -f test-cockpit-docker")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainerActions(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-actions busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-actions']", "Running")

            # pause and resume the container from the row kebab menu
            b.click("#containers-containers tr[data-row-name='0-test-actions'] .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Pause')")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-actions']", "Paused")

            # the Details tab shows the actual state, not a generic "Exited"
            b.click("#containers-containers tr[data-row-name='0-test-actions'] .pf-v6-c-table__toggle button")
            b.wait_in_text("#containers-containers .container-details-state", "Paused")
            b.click("#containers-containers tr[data-row-name='0-test-actions'] .pf-v6-c-table__toggle button")

            b.click("#containers-containers tr[data-row-name='0-test-actions'] .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Resume')")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-actions']", "Running")
        finally:
            m.execute("docker rm -f test-actions")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainerDetails(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-details busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_visible("#containers-containers tr[data-row-name='0-test-details']")

            # expand the row; the Details tab shows the image metadata
            b.click("#containers-containers tr[data-row-name='0-test-details'] .pf-v6-c-table__toggle button")
            b.wait_in_text("#containers-containers .container-details-basic", "busybox")
            b.wait_in_text("#containers-containers .container-details-state", "Up since:")
        finally:
            m.execute("docker rm -f test-details")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainersFilters(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-running busybox sleep 10000")
            m.execute("docker run --name test-exited busybox true")
            b.reload()
            b.enter_page("/cockpit-docker")

            # both containers are listed with their state
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-running']", "Running")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-exited']", "Exited")

            # the "Only running" filter hides stopped containers
            b.set_val("#containers-containers-filter", "running")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-running']", "Running")
            b.wait_not_present("#containers-containers tr[data-row-name='0-test-exited']")
            b.set_val("#containers-containers-filter", "all")
            b.wait_visible("#containers-containers tr[data-row-name='0-test-exited']")

            # the text search filters the listing
            b.set_input_text("#containers-filter input", "test-exited")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-exited']", "Exited")
            b.wait_not_present("#containers-containers tr[data-row-name='0-test-running']")
            b.set_input_text("#containers-filter input", "")
            b.wait_visible("#containers-containers tr[data-row-name='0-test-running']")
        finally:
            m.execute("docker rm -f test-running test-exited")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainerStopStartRestart(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-restart busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            row = "#containers-containers tr[data-row-name='0-test-restart']"
            b.wait_in_text(row, "Running")

            # stop the container from the row kebab menu
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Stop')")
            b.wait_in_text(row, "Exited")

            # start it again
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Start')")
            b.wait_in_text(row, "Running")

            # and restart it
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Restart')")
            b.wait_in_text(row, "Running")

            # force restart and force stop use a zero timeout
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Force restart')")
            b.wait_in_text(row, "Running")

            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Force stop')")
            b.wait_in_text(row, "Exited")

            # start it again so the cleanup removes a running container
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Start')")
            b.wait_in_text(row, "Running")
        finally:
            m.execute("docker rm -f test-restart")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainerRename(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run --name test-oldname busybox true")
            b.reload()
            b.enter_page("/cockpit-docker")
            row = "#containers-containers tr[data-row-name='0-test-oldname']"
            b.wait_in_text(row, "Exited")

            # renaming is only offered for stopped containers
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Rename')")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_in_text(".pf-v6-c-modal-box", "Rename container test-oldname")
            b.set_input_text("#rename-dialog-container-name", "test-renamed")
            b.click("#btn-rename-dialog-container")
            b.wait_not_present(".pf-v6-c-modal-box")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_visible("#containers-containers tr[data-row-name='0-test-renamed']")
            b.wait_not_present("#containers-containers tr[data-row-name='0-test-oldname']")
        finally:
            m.execute("docker rm -f test-renamed test-oldname")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainerForceDelete(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-forcedelete busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            row = "#containers-containers tr[data-row-name='0-test-forcedelete']"
            b.wait_in_text(row, "Running")

            # deleting a running container asks for a force-remove confirmation
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Delete')")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_in_text(".pf-v6-c-modal-box", "Delete test-forcedelete?")
            b.click(".pf-v6-c-modal-box__footer button:contains('Force delete')")
            b.wait_not_present(".pf-v6-c-modal-box")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present("#containers-containers tr[data-row-name='0-test-forcedelete']")
        finally:
            m.execute("docker rm -f test-forcedelete")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainerCommit(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-commit busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            row = "#containers-containers tr[data-row-name='0-test-commit']"
            b.wait_visible(row)

            # committing without an image name is rejected
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Commit')")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_text(".pf-v6-c-modal-box__title", "Commit container")
            b.click(".btn-ctr-commit")
            b.wait_in_text(".pf-v6-c-modal-box", "Image name is required")

            # commit the container to a new image
            b.set_input_text("#commit-dialog-image-name", "test-commit-image")
            b.click(".btn-ctr-commit")
            b.wait_not_present(".pf-v6-c-modal-box")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
            b.wait_visible("#containers-images tr[data-row-name='0-test-commit-image:latest']")
        finally:
            m.execute("docker rmi test-commit-image:latest || true")
            m.execute("docker rm -f test-commit")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainerIntegration(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-integration -p 8080:80 "
                      "-e FOO=bar -v /tmp/hostvol:/data busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            row = "#containers-containers tr[data-row-name='0-test-integration']"
            b.wait_visible(row)

            # the Integration tab shows ports, volumes and environment variables
            b.click(row + " .pf-v6-c-table__toggle button")
            b.click("#containers-containers .pf-v6-c-tabs__item button:contains('Integration')")
            b.wait_in_text("#containers-containers .container-integration-ports", "8080")
            b.wait_in_text("#containers-containers .container-integration-ports", "80/tcp")
            b.wait_in_text("#containers-containers .container-integration-volumes", "/tmp/hostvol")
            b.wait_in_text("#containers-containers .container-integration-volumes", "/data")
            b.wait_in_text("#containers-containers .container-integration-envs", "FOO=bar")
        finally:
            m.execute("docker rm -f test-integration")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testPortRanges(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            # consecutive container ports are collapsed into a single range in
            # the Integration tab, even when the daemon reports an interleaved
            # protocol (80/udp) between them
            m.execute("docker run -d --name test-ports -p 8080:80 -p 8081:81 "
                      "-p 8080:80/udp busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            row = "#containers-containers tr[data-row-name='0-test-ports']"
            b.wait_visible(row)

            b.click(row + " .pf-v6-c-table__toggle button")
            b.click("#containers-containers .pf-v6-c-tabs__item button:contains('Integration')")
            b.wait_in_text("#containers-containers .container-integration-ports", "80-81/tcp")
            b.wait_in_text("#containers-containers .container-integration-ports", "80/udp")
        finally:
            m.execute("docker rm -f test-ports")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainerHealth(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-health --health-cmd='true' "
                      "--health-interval=1s --health-retries=3 --health-timeout=1s busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            row = "#containers-containers tr[data-row-name='0-test-health']"
            b.wait_visible(row)

            # the container becomes healthy shortly after starting
            b.wait_in_text(row, "Healthy")

            # the Health check tab is offered in the expanded row
            b.click(row + " .pf-v6-c-table__toggle button")
            b.wait_visible("#containers-containers .pf-v6-c-tabs__item button:contains('Health check')")
        finally:
            m.execute("docker rm -f test-health")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainerPrune(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run --name test-prune-a busybox true")
            m.execute("docker run --name test-prune-b busybox true")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_visible("#containers-containers tr[data-row-name='0-test-prune-a']")

            # prune the stopped containers from the card header menu
            b.click("#containers-actions-dropdown")
            b.click("#prune-unused-containers-button")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_in_text(".pf-v6-c-modal-box", "Prune unused containers")
            b.click("#btn-img-delete")
            b.wait_not_present(".pf-v6-c-modal-box")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present("#containers-containers tr[data-row-name='0-test-prune-a']")
            b.wait_not_present("#containers-containers tr[data-row-name='0-test-prune-b']")
        finally:
            m.execute("docker rm -f test-prune-a test-prune-b")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testStartStopAll(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-bulk-a busybox sleep 10000")
            m.execute("docker run -d --name test-bulk-b busybox sleep 10000")
            # a container that was created but never started
            m.execute("docker create --name test-bulk-c busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-bulk-a']", "Running")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-bulk-b']", "Running")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-bulk-c']", "Created")

            # stopping all containers stops the running ones and leaves the
            # already-stopped one alone
            b.click("#containers-actions-dropdown")
            b.click("#stop-all-containers-button")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-bulk-a']", "Exited")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-bulk-b']", "Exited")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-bulk-c']", "Created")

            # starting all containers starts the stopped ones, including the
            # never-started one
            b.click("#containers-actions-dropdown")
            b.click("#start-all-containers-button")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-bulk-a']", "Running")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-bulk-b']", "Running")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-bulk-c']", "Running")
        finally:
            m.execute("docker rm -f test-bulk-a test-bulk-b test-bulk-c")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testImageCreateRun(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
            b.wait_visible("#containers-images .image-name")
            b.click("#containers-images .ct-container-create")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_text(".pf-v6-c-modal-box__title", "Create container")

            # create and run the pre-pulled busybox image, with a command that
            # keeps the container running
            b.set_input_text("#run-image-dialog-name", "test-from-image")
            b.set_input_text("#run-image-dialog-command", "sleep 10000")
            b.click("#create-image-create-run-btn")
            b.wait_not_present(".pf-v6-c-modal-box")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-from-image']", "Running")
        finally:
            m.execute("docker rm -f test-from-image")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testCreateStackDialog(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            # opening the create-stack dialog from the containers toolbar
            b.click("#containers-containers-create-stack-btn")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_text(".pf-v6-c-modal-box__title", "Create stack")
            b.wait_visible("#create-stack-dialog-name")

            # the project name is required and must not contain spaces
            b.set_input_text("#create-stack-dialog-name", "")
            b.wait_in_text(".pf-v6-c-modal-box", "Project name is required.")
            b.set_input_text("#create-stack-dialog-name", "has space")
            b.wait_in_text(".pf-v6-c-modal-box", "Invalid characters")

            # a valid name clears the error and saves the stack files, which
            # show up in the inactive stacks section
            b.set_input_text("#create-stack-dialog-name", "test-ui-stack")
            b.wait_not_in_text(".pf-v6-c-modal-box", "Invalid characters")
            b.click("#create-stack-dialog-create-btn")
            b.wait_not_present(".pf-v6-c-modal-box")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_in_text(".container-inactive-stacks", "test-ui-stack")
            b.wait_visible("tr[data-row-name='test-ui-stack']")
        finally:
            # remove the stack directory created by the dialog
            m.execute("rm -rf /var/lib/cockpit-docker/stacks/test-ui-stack")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-inactive-stacks")

    def testRemoveInactiveStack(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            # create an inactive stack on disk, so it shows up in the listing
            m.execute('''mkdir -p /var/lib/cockpit-docker/stacks/test-remove-stack
cat > /var/lib/cockpit-docker/stacks/test-remove-stack/docker-compose.yml <<'EOF'
services:
  web:
    image: busybox
    command: ["sleep", "3600"]
EOF''')
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_in_text(".container-inactive-stacks", "test-remove-stack")

            # removing the stack asks for confirmation before deleting the
            # compose files, and must make the stack disappear immediately;
            # when it was the only stack the whole section disappears with it
            b.click("#inactive-stack-actions-test-remove-stack")
            b.click(".pf-v6-c-menu__item:contains('Remove')")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_in_text(".pf-v6-c-modal-box", "Remove stack test-remove-stack?")

            # cancelling keeps the stack and its files
            b.click(".pf-v6-c-modal-box__footer button:contains('Cancel')")
            b.wait_not_present(".pf-v6-c-modal-box")
            b.wait_in_text(".container-inactive-stacks", "test-remove-stack")

            # confirming the dialog deletes the stack files
            b.click("#inactive-stack-actions-test-remove-stack")
            b.click(".pf-v6-c-menu__item:contains('Remove')")
            b.wait_visible(".pf-v6-c-modal-box")
            b.click(".pf-v6-c-modal-box__footer button:contains('Remove')")
            b.wait_not_present("tr[data-row-name='test-remove-stack']")
        finally:
            m.execute("rm -rf /var/lib/cockpit-docker/stacks/test-remove-stack")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-inactive-stacks")

    def testStackLifecycle(self):
        b = self.browser
        m = self.machine

        # create the stack's compose files under the plugin's stack directory
        m.execute('''mkdir -p /var/lib/cockpit-docker/stacks/test-stack
cat > /var/lib/cockpit-docker/stacks/test-stack/docker-compose.yml <<'EOF'
services:
  web:
    image: busybox
    command: ["sleep", "3600"]
EOF''')

        self.login_and_go("/cockpit-docker")
        b.reload()
        b.enter_page("/cockpit-docker")
        try:
            # the not-yet-started stack is listed under inactive stacks
            b.wait_in_text(".container-inactive-stacks", "test-stack")
            b.wait_visible("tr[data-row-name='test-stack']")

            # its edit dialog is prefilled with the stack name
            b.click("#inactive-stack-actions-test-stack")
            b.click(".pf-v6-c-menu__item:contains('Edit')")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_text(".pf-v6-c-modal-box__title", "Edit stack test-stack")
            b.click(".btn-cancel")
            b.wait_not_present(".pf-v6-c-modal-box")

            # starting the stack brings its container into the listing
            b.click("#inactive-stack-start-test-stack")
            b.wait_visible("#table-test-stack")
            b.wait_in_text("#table-test-stack .stack-name", "test-stack")
            b.wait_in_text("#table-test-stack .ct-badge-stack-running", "Running")
            b.wait_visible("#table-test-stack tr[data-row-name='0-test-stack-web-1']")

            # stopping the stack marks it stopped, but keeps its containers
            b.click("#stack-actions-dropdown-test-stack-web-1")
            b.click(".pf-v6-c-menu__item.stack-action-stop")
            b.wait_in_text("#table-test-stack .ct-badge-stack-stopped", "Stopped")
            b.wait_visible("#table-test-stack tr[data-row-name='0-test-stack-web-1']")

            # ... and starting it again returns it to running
            b.click("#stack-actions-dropdown-test-stack-web-1")
            b.click(".pf-v6-c-menu__item.stack-action-start")
            b.wait_in_text("#table-test-stack .ct-badge-stack-running", "Running")

            # removing the stack deletes the containers but keeps the files,
            # so it moves back to the inactive stacks section
            b.click("#stack-actions-dropdown-test-stack-web-1")
            b.click(".pf-v6-c-menu__item.stack-action-remove")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_in_text(".pf-v6-c-modal-box", "Remove stack?")
            b.click(".pf-v6-c-modal-box__footer button:contains('Remove')")
            b.wait_not_present(".pf-v6-c-modal-box")
            # the containers are force-deleted, their removal cascades through
            # the event stream; reload for a deterministic listing
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_in_text(".container-inactive-stacks", "test-stack")
        finally:
            # bring down any leftover containers and remove the stack files
            m.execute("cd /var/lib/cockpit-docker/stacks/test-stack && "
                      "docker compose down --remove-orphans >/dev/null 2>&1 || true")
            m.execute("rm -rf /var/lib/cockpit-docker/stacks/test-stack")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-inactive-stacks")

    def testImages(self):
        b = self.browser

        self.login_and_go("/cockpit-docker")

        # the image listing is collapsed by default; expand it
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        row = "#containers-images tr[data-row-name='0-busybox:latest']"
        b.wait_visible(row)

        # the pre-pulled busybox image is listed with its metadata
        b.wait_in_text(row, "busybox:latest")
        b.wait_in_text(row, "system")
        b.wait_in_text(row, "unused")
        b.wait_in_text("#containers-images", "1 image total")

        # the listing can be collapsed again
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        b.wait_not_visible("#containers-images .image-name")

    def testImageDetails(self):
        b = self.browser

        self.login_and_go("/cockpit-docker")
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        b.wait_visible("#containers-images .image-name")

        # expand the image row
        b.click("#containers-images tr[data-row-name='0-busybox:latest'] .pf-v6-c-table__toggle button")
        b.wait_visible("#containers-images .pf-v6-c-tabs__list")

        # the Details tab shows the image metadata
        b.wait_in_text("#containers-images .image-details", "busybox:latest")
        b.wait_in_text("#containers-images .image-details", "Command")

        # the History tab shows the image build history
        b.click("#containers-images .pf-v6-c-tabs__item button:contains('History')")
        b.wait_in_text("#containers-images .ct-listing-panel-body .pf-v6-c-table", "Created by")

    def testImageRunDialog(self):
        b = self.browser

        self.login_and_go("/cockpit-docker")
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        b.wait_visible("#containers-images .image-name")

        # opening the run-image dialog from the row action
        b.click("#containers-images .ct-container-create")
        b.wait_visible(".pf-v6-c-modal-box")
        b.wait_text(".pf-v6-c-modal-box__title", "Create container")
        b.wait_visible("#run-image-dialog-name")
        # cancel without creating anything
        b.click(".btn-cancel")
        b.wait_not_present(".pf-v6-c-modal-box")

    def testPortValidation(self):
        b = self.browser

        self.login_and_go("/cockpit-docker")
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        b.wait_visible("#containers-images .image-name")
        b.click("#containers-images .ct-container-create")
        b.wait_visible(".pf-v6-c-modal-box")

        # add a port mapping and give the container port a valid value
        b.click(".pf-v6-c-modal-box .pf-v6-c-tabs__item button:contains('Integration')")
        b.click(".publish-port-form .btn-add")
        b.wait_visible("#run-image-dialog-publish-0-container-port")
        b.set_input_text("#run-image-dialog-publish-0-container-port", "80")

        # a fractional host port must be rejected instead of being silently
        # truncated to port 1 by parseInt
        b.set_input_text("#run-image-dialog-publish-0-host-port", "1.5")
        b.wait_in_text("#run-image-dialog-publish-0-host-port-group", "1 to 65535")

        # a valid host port clears the error
        b.set_input_text("#run-image-dialog-publish-0-host-port", "8080")
        b.wait_not_in_text("#run-image-dialog-publish-0-host-port-group", "1 to 65535")

        b.click(".btn-cancel")
        b.wait_not_present(".pf-v6-c-modal-box")

    def testPortBindings(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
            b.wait_visible("#containers-images .image-name")
            b.click("#containers-images .ct-container-create")
            b.wait_visible(".pf-v6-c-modal-box")

            # keep the container running, so it can be inspected afterwards
            b.set_input_text("#run-image-dialog-name", "test-portbind")
            b.set_input_text("#run-image-dialog-command", "sleep 10000")

            # map two different host ports to the same container port
            b.click(".pf-v6-c-modal-box .pf-v6-c-tabs__item button:contains('Integration')")
            b.click(".publish-port-form .btn-add")
            b.wait_visible("#run-image-dialog-publish-0-container-port")
            b.set_input_text("#run-image-dialog-publish-0-container-port", "80")
            b.set_input_text("#run-image-dialog-publish-0-host-port", "8080")
            b.click(".publish-port-form .btn-add")
            b.wait_visible("#run-image-dialog-publish-1-container-port")
            b.set_input_text("#run-image-dialog-publish-1-container-port", "80")
            b.set_input_text("#run-image-dialog-publish-1-host-port", "8081")

            b.click("#create-image-create-run-btn")
            b.wait_not_present(".pf-v6-c-modal-box")

            # both host ports must be bound to the container's port 80
            output = m.execute("docker port test-portbind 80")
            self.assertIn("0.0.0.0:8080", output)
            self.assertIn("0.0.0.0:8081", output)
        finally:
            m.execute("docker rm -f test-portbind || true")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testPortMap(self):
        b = self.browser
        m = self.machine

        # the host ports of the rows, in DOM order
        def wait_ports(expected):
            js = ("JSON.stringify(Array.from(document.querySelectorAll('#port-map-table tbody tr'))"
                  ".map(tr => tr.children[0].textContent.trim()))"
                  " === JSON.stringify(" + testlib.jsquote(expected) + ")")
            b.wait_js_cond(js)

        def wait_names(expected):
            js = ("JSON.stringify(Array.from(document.querySelectorAll('#port-map-table tbody tr'))"
                  ".map(tr => (tr.children[1].querySelector('.container-name')?.textContent || '').trim()))"
                  " === JSON.stringify(" + testlib.jsquote(expected) + ")")
            b.wait_js_cond(js)

        self.login_and_go("/cockpit-docker")
        try:
            # three running containers with published host ports; the names sort
            # differently than the ports, so both sort orders are observable
            # (avoid port 9090, which the cockpit web service uses on the VM)
            m.execute("docker run -d --name test-portmap-c -p 7070:70 busybox sleep 10000")
            m.execute("docker run -d --name test-portmap-a -p 9080:80 busybox sleep 10000")
            m.execute("docker run -d --name test-portmap-b -p 9081:81 -p 9082:82 busybox sleep 10000")
            # a stopped container whose port is only configured, not bound
            m.execute("docker run --name test-portmap-stopped -p 7090:90 busybox true")
            # two inactive stacks that both reserve host port 7070, i.e. a
            # port conflict between them and with the active container
            m.execute('''mkdir -p /var/lib/cockpit-docker/stacks/test-portmap-stack
cat > /var/lib/cockpit-docker/stacks/test-portmap-stack/docker-compose.yml <<'EOF'
services:
  web:
    image: busybox
    ports:
      - "7070:80"
EOF
mkdir -p /var/lib/cockpit-docker/stacks/test-portmap-stack2
cat > /var/lib/cockpit-docker/stacks/test-portmap-stack2/docker-compose.yml <<'EOF'
services:
  api:
    image: busybox
    ports:
      - "7070:80"
EOF''')
            # a stack that was started and then stopped: it still has
            # containers, so it is not an inactive stack, but its container
            # is stopped and occupies host port 7080
            m.execute('''mkdir -p /var/lib/cockpit-docker/stacks/test-portmap-stopped-stack
cat > /var/lib/cockpit-docker/stacks/test-portmap-stopped-stack/docker-compose.yml <<'EOF'
services:
  db:
    image: busybox
    command: ["sleep", "3600"]
    ports:
      - "7080:80"
EOF
cd /var/lib/cockpit-docker/stacks/test-portmap-stopped-stack && docker compose up -d && docker compose stop''')
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_visible("tr[data-row-name='0-test-portmap-a']")

            # open the port map from the containers header menu
            b.click("#containers-actions-dropdown")
            b.click("#port-map-button")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_text(".pf-v6-c-modal-box__title", "Port map")

            # the running containers' ports are listed, sorted by host port,
            # each row showing the container name, its image below it and the port
            wait_ports(["7070/tcp", "9080/tcp", "9081/tcp", "9082/tcp"])
            b.wait_in_text("#port-map-table", "test-portmap-c")
            b.wait_in_text("#port-map-table", "test-portmap-a")
            b.wait_in_text("#port-map-table", "test-portmap-b")
            b.wait_in_text("#port-map-table", "busybox")
            # stopped containers, stopped stacks and inactive stacks are not
            # included yet
            b.wait_not_in_text("#port-map-table", "inactive stack")
            b.wait_not_in_text("#port-map-table", "test-portmap-stack")
            b.wait_not_in_text("#port-map-table", "7080/tcp")
            b.wait_not_in_text("#port-map-table", "7090/tcp")

            # including stopped containers and inactive stacks shows the
            # reserved ports of everything not running, sorted by host port
            b.set_checked("#port-map-include-inactive", True)
            wait_ports(["7070/tcp", "7070/tcp", "7070/tcp", "7080/tcp", "7090/tcp",
                        "9080/tcp", "9081/tcp", "9082/tcp"])
            wait_names([
                "test-portmap-c", "web", "api", "test-portmap-stopped-stack-db-1",
                "test-portmap-stopped", "test-portmap-a", "test-portmap-b", "test-portmap-b",
            ])
            # the stopped container and the stopped stack's container are marked
            b.wait_in_text("#port-map-table tr[data-row-name='test-portmap-stopped'] .ct-portmap-inactive",
                           "stopped")
            b.wait_in_text("#port-map-table tr[data-row-name='test-portmap-stopped-stack-db-1'] .ct-portmap-inactive",
                           "stopped")
            b.wait_in_text("#port-map-table tr[data-row-name='test-portmap-stopped-stack-db-1']",
                           "test-portmap-stopped-stack")
            # the two inactive stacks conflict over host port 7070 (also used
            # by the running container) and are called out
            b.wait_in_text("#port-map-table", "inactive stack")
            b.wait_in_text("#port-map-table", "test-portmap-stack")
            b.wait_in_text("#port-map-table", "test-portmap-stack2")
            b.wait_js_cond("document.querySelectorAll('#port-map-table .ct-portmap-conflict').length === 2")

            # grouping shows one row per container, with all of its ports
            b.set_checked("#port-map-group-containers", True)
            wait_ports(["7070/tcp", "7070/tcp", "7070/tcp", "7080/tcp", "7090/tcp",
                        "9080/tcp", "9081/tcp, 9082/tcp"])
            wait_names([
                "test-portmap-c", "web", "api", "test-portmap-stopped-stack-db-1",
                "test-portmap-stopped", "test-portmap-a", "test-portmap-b",
            ])

            # ungrouping again and sorting by container name reorders the rows
            b.set_checked("#port-map-group-containers", False)
            b.click("#port-map-table thead th:nth-child(2) button")
            wait_names([
                "api", "test-portmap-a", "test-portmap-b", "test-portmap-b",
                "test-portmap-c", "test-portmap-stopped",
                "test-portmap-stopped-stack-db-1", "web",
            ])
        finally:
            m.execute("cd /var/lib/cockpit-docker/stacks/test-portmap-stopped-stack && "
                      "docker compose down --remove-orphans >/dev/null 2>&1 || true")
            m.execute("docker rm -f test-portmap-a test-portmap-b test-portmap-c test-portmap-stopped")
            m.execute("rm -rf /var/lib/cockpit-docker/stacks/test-portmap-stack "
                      "/var/lib/cockpit-docker/stacks/test-portmap-stack2 "
                      "/var/lib/cockpit-docker/stacks/test-portmap-stopped-stack")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testImageDeleteTag(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            # add an extra tag to the pre-pulled busybox image
            m.execute("docker tag busybox test-extra:latest")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
            row = "#containers-images tr[data-row-name='0-busybox:latest']"
            b.wait_visible(row)

            # the delete dialog lists every tag of the image
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Delete')")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_in_text(".pf-v6-c-modal-box", "Multiple tags exist for this image")
            b.wait_visible("#delete-busybox\\:latest")
            b.wait_visible("#delete-test-extra\\:latest")

            # remove only the extra tag, keeping busybox:latest
            b.click("#delete-busybox\\:latest")
            b.click("#delete-test-extra\\:latest")
            b.click("#btn-img-delete")
            b.wait_not_present(".pf-v6-c-modal-box")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
            b.wait_visible("#containers-images tr[data-row-name='0-busybox:latest']")

            # reopening the delete dialog now shows a single tag
            b.click("#containers-images tr[data-row-name='0-busybox:latest'] .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Delete')")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_not_in_text(".pf-v6-c-modal-box", "Multiple tags exist for this image")
            b.wait_in_text(".pf-v6-c-modal-box", "busybox:latest")
            b.click(".pf-v6-c-modal-box__footer button:contains('Cancel')")
            b.wait_not_present(".pf-v6-c-modal-box")
        finally:
            # make sure the extra tag is gone and busybox stays around
            m.execute("docker rmi test-extra:latest || true")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_visible("#containers-images")

    def testImageDeleteInUse(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-imguse busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
            row = "#containers-images tr[data-row-name='0-busybox:latest']"
            b.wait_visible(row)

            # deleting an image a running container uses must be confirmed
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Delete')")
            b.wait_visible(".pf-v6-c-modal-box")
            b.click("#btn-img-delete")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_in_text(".pf-v6-c-modal-box", "Delete busybox:latest?")

            # back out without force-removing the image
            b.click(".pf-v6-c-modal-box__footer button:contains('Cancel')")
            b.wait_not_present(".pf-v6-c-modal-box")
            b.wait_visible("#containers-images tr[data-row-name='0-busybox:latest']")
        finally:
            m.execute("docker rm -f test-imguse")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testImageUpdates(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            # A locally built image has no registry digest recorded, so the
            # update check never runs for it and no "Update available" badge is
            # shown. This also guards against the listing breaking when the
            # registry lookup fails (no buildx, no network, unknown registry).
            m.execute("docker build -t update-badgetest:latest - <<'EOF'\nFROM busybox\nEOF")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
            row = "#containers-images tr[data-row-name='0-update-badgetest:latest']"
            b.wait_visible(row)
            b.wait_not_present(row + " .ct-badge-image-update")
        finally:
            m.execute("docker rmi update-badgetest:latest || true")
            # drop any dangling <none> image the build left behind, so the
            # shared nondestructive VM is left in a pristine state
            m.execute("docker image prune -f || true")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_visible("#containers-images")

    def testImageUpdateAvailable(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            # A registry on localhost acts as a deterministic stand-in for
            # Docker Hub, so the test does not depend on external images or
            # their state. It needs the network only to pull the registry
            # image; when that is not available the test is skipped.
            try:
                m.execute("docker run -d -p 5000:5000 --name test-updreg registry:2")
            except Exception as ex:
                self.skipTest(f"registry:2 could not be pulled: {ex}")
            # v1 is pushed as :latest, so the local image records its digest
            m.execute("docker build -t localhost:5000/updtest:latest - <<'EOF'\n"
                      "FROM busybox\n"
                      "RUN echo v1 > /marker\n"
                      "EOF")
            m.execute("docker push localhost:5000/updtest:latest")
            # keep v1 alive under a backup tag, then push a newer v2 as
            # :latest; the registry now serves the newer digest while the
            # locally tagged image still records the old one
            m.execute("docker tag localhost:5000/updtest:latest localhost:5000/updtest:v1backup")
            m.execute("docker build -t localhost:5000/updtest:latest - <<'EOF'\n"
                      "FROM busybox\n"
                      "RUN echo v2 > /marker\n"
                      "EOF")
            m.execute("docker push localhost:5000/updtest:latest")
            m.execute("docker tag localhost:5000/updtest:v1backup localhost:5000/updtest:latest")

            b.reload()
            b.enter_page("/cockpit-docker")
            b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
            row = "#containers-images tr[data-row-name='0-localhost:5000/updtest:latest']"
            b.wait_visible(row)
            # the local digest no longer matches the registry's, so an update
            # badge is shown; the assertions are scoped to this row and the
            # header label, because other images (e.g. a busybox:latest that
            # moved in its registry since the image was built) may legitimately
            # show a badge as well
            b.wait_visible(row + " .ct-badge-image-update")
            b.wait_in_text(row + " .ct-badge-image-update", "Update available")
            b.wait_visible("#containers-images [data-testid='images-update-count']")
        finally:
            m.execute("docker rm -f test-updreg || true")
            m.execute("docker rmi localhost:5000/updtest:latest localhost:5000/updtest:v1backup || true")
            m.execute("docker rmi registry:2 || true")
            # drop the dangling <none> images the builds left behind, so the
            # shared nondestructive VM is left in a pristine state
            m.execute("docker image prune -f || true")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_visible("#containers-images")


# This test gets its own fresh VM (not @nondestructive) because it makes
# permanent changes: it hides the docker CLI and stops the docker daemon.
class TestDockerNotInstalled(testlib.MachineCase):
    def testDockerNotInstalled(self):
        b = self.browser
        m = self.machine

        # simulate a system without docker: no daemon and no docker CLI
        m.execute("systemctl mask docker docker.socket")
        m.execute("systemctl stop docker docker.socket")
        m.execute("mv /usr/bin/docker /usr/bin/docker.example")

        self.login_and_go("/cockpit-docker")

        b.wait_in_text(".pf-v6-c-empty-state__title", "Docker is not installed")
        b.wait_in_text(".pf-v6-c-empty-state__body", "Docker is not installed on this system.")
        b.wait_in_text(".pf-v6-c-empty-state__body", "See Docker installation instructions")


if __name__ == '__main__':
    testlib.test_main()
