#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/common/pywrap", sys.argv)

# Run this with --help to see available options for tracing and debugging
# See https://github.com/cockpit-project/cockpit/blob/main/test/common/testlib.py
# "class Browser" and "class MachineCase" for the available API.

import testlib


# Nondestructive tests all run in the same running VM. This allows them to run in Packit, Fedora, and
# RHEL dist-git gating. They must not permanently change any file or configuration on the system in a
# way that influences other tests.
@testlib.nondestructive
class TestApplication(testlib.MachineCase):
    def testBasic(self):
        b = self.browser

        self.login_and_go("/cockpit-docker")

        # both main listing cards are shown
        b.wait_in_text("#containers-containers .pf-v6-c-card__title", "Containers")
        b.wait_in_text("#containers-images .pf-v6-c-card__title", "Images")

        # no containers have been created yet
        b.wait_in_text("#containers-containers .pf-v6-c-empty-state", "No containers")

        # the image listing is collapsed by default; expand it
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        # the busybox image is pre-pulled into the test VM
        b.wait_in_text("#containers-images .image-name", "busybox")

    def testContainers(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        b.wait_in_text("#containers-images .image-name", "busybox")

        try:
            # start a container on the machine; it should show up in the UI
            m.execute("docker run -d --name test-cockpit-docker busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_in_text(".container-name", "test-cockpit-docker")
            b.wait_visible("tr[data-row-name='0-test-cockpit-docker']")
        finally:
            # clean up so the shared machine stays in a pristine state
            m.execute("docker rm -f test-cockpit-docker")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testImages(self):
        b = self.browser

        self.login_and_go("/cockpit-docker")

        # the image listing is collapsed by default; expand it
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        row = "#containers-images tr[data-row-name='0-busybox:latest']"
        b.wait_visible(row)

        # the pre-pulled busybox image is listed with its metadata
        b.wait_in_text(row, "busybox:latest")
        b.wait_in_text(row, "system")
        b.wait_in_text(row, "unused")
        b.wait_in_text("#containers-images", "1 image total")

        # the listing can be collapsed again
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        b.wait_not_visible("#containers-images .image-name")

    def testImageDetails(self):
        b = self.browser

        self.login_and_go("/cockpit-docker")
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        b.wait_visible("#containers-images .image-name")

        # expand the image row
        b.click("#containers-images tr[data-row-name='0-busybox:latest'] .pf-v6-c-table__toggle button")
        b.wait_visible("#containers-images .pf-v6-c-tabs__list")

        # the Details tab shows the image metadata
        b.wait_in_text("#containers-images .image-details", "busybox:latest")
        b.wait_in_text("#containers-images .image-details", "Command")

        # the History tab shows the image build history
        b.click("#containers-images .pf-v6-c-tabs__item button:contains('History')")
        b.wait_in_text("#containers-images .ct-listing-panel-body .pf-v6-c-table", "Created by")

    def testImageRunDialog(self):
        b = self.browser

        self.login_and_go("/cockpit-docker")
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        b.wait_visible("#containers-images .image-name")

        # opening the run-image dialog from the row action
        b.click("#containers-images .ct-container-create")
        b.wait_visible(".pf-v6-c-modal-box")
        b.wait_text(".pf-v6-c-modal-box__title", "Create container")
        b.wait_visible("#run-image-dialog-name")
        # cancel without creating anything
        b.click(".btn-cancel")
        b.wait_not_present(".pf-v6-c-modal-box")


# This test gets its own fresh VM (not @nondestructive) because it makes
# permanent changes: it hides the docker CLI and stops the docker daemon.
class TestDockerNotInstalled(testlib.MachineCase):
    def testDockerNotInstalled(self):
        b = self.browser
        m = self.machine

        # simulate a system without docker: no daemon and no docker CLI
        m.execute("systemctl mask docker docker.socket")
        m.execute("systemctl stop docker docker.socket")
        m.execute("mv /usr/bin/docker /usr/bin/docker.example")

        self.login_and_go("/cockpit-docker")

        b.wait_in_text(".pf-v6-c-empty-state__title", "Docker is not installed")
        b.wait_in_text(".pf-v6-c-empty-state__body", "Docker is not installed on this system.")
        b.wait_in_text(".pf-v6-c-empty-state__body", "See Docker installation instructions")


if __name__ == '__main__':
    testlib.test_main()
