#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/common/pywrap", sys.argv)

# Run this with --help to see available options for tracing and debugging
# See https://github.com/cockpit-project/cockpit/blob/main/test/common/testlib.py
# "class Browser" and "class MachineCase" for the available API.

import testlib


# Nondestructive tests all run in the same running VM. This allows them to run in Packit, Fedora, and
# RHEL dist-git gating. They must not permanently change any file or configuration on the system in a
# way that influences other tests.
@testlib.nondestructive
class TestApplication(testlib.MachineCase):
    def testBasic(self):
        b = self.browser

        self.login_and_go("/cockpit-docker")

        # both main listing cards are shown
        b.wait_in_text("#containers-containers .pf-v6-c-card__title", "Containers")
        b.wait_in_text("#containers-images .pf-v6-c-card__title", "Images")

        # no containers have been created yet
        b.wait_in_text("#containers-containers .pf-v6-c-empty-state", "No containers")

        # the image listing is collapsed by default; expand it
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        # the busybox image is pre-pulled into the test VM
        b.wait_in_text("#containers-images .image-name", "busybox")

    def testContainers(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        b.wait_in_text("#containers-images .image-name", "busybox")

        try:
            # start a container on the machine; it should show up in the UI
            m.execute("docker run -d --name test-cockpit-docker busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_in_text(".container-name", "test-cockpit-docker")
            b.wait_visible("tr[data-row-name='0-test-cockpit-docker']")
        finally:
            # clean up so the shared machine stays in a pristine state
            m.execute("docker rm -f test-cockpit-docker")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainerActions(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-actions busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-actions']", "Running")

            # pause and resume the container from the row kebab menu
            b.click("#containers-containers tr[data-row-name='0-test-actions'] .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Pause')")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-actions']", "Paused")

            b.click("#containers-containers tr[data-row-name='0-test-actions'] .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Resume')")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-actions']", "Running")
        finally:
            m.execute("docker rm -f test-actions")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainerDetails(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-details busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_visible("#containers-containers tr[data-row-name='0-test-details']")

            # expand the row; the Details tab shows the image metadata
            b.click("#containers-containers tr[data-row-name='0-test-details'] .pf-v6-c-table__toggle button")
            b.wait_in_text("#containers-containers .container-details-basic", "busybox")
            b.wait_in_text("#containers-containers .container-details-state", "Up since:")
        finally:
            m.execute("docker rm -f test-details")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainersFilters(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-running busybox sleep 10000")
            m.execute("docker run --name test-exited busybox true")
            b.reload()
            b.enter_page("/cockpit-docker")

            # both containers are listed with their state
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-running']", "Running")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-exited']", "Exited")

            # the "Only running" filter hides stopped containers
            b.set_val("#containers-containers-filter", "running")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-running']", "Running")
            b.wait_not_present("#containers-containers tr[data-row-name='0-test-exited']")
            b.set_val("#containers-containers-filter", "all")
            b.wait_visible("#containers-containers tr[data-row-name='0-test-exited']")

            # the text search filters the listing
            b.set_input_text("#containers-filter input", "test-exited")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-exited']", "Exited")
            b.wait_not_present("#containers-containers tr[data-row-name='0-test-running']")
            b.set_input_text("#containers-filter input", "")
            b.wait_visible("#containers-containers tr[data-row-name='0-test-running']")
        finally:
            m.execute("docker rm -f test-running test-exited")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainerStopStartRestart(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-restart busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            row = "#containers-containers tr[data-row-name='0-test-restart']"
            b.wait_in_text(row, "Running")

            # stop the container from the row kebab menu
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Stop')")
            b.wait_in_text(row, "Exited")

            # start it again
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Start')")
            b.wait_in_text(row, "Running")

            # and restart it
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Restart')")
            b.wait_in_text(row, "Running")
        finally:
            m.execute("docker rm -f test-restart")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainerRename(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run --name test-oldname busybox true")
            b.reload()
            b.enter_page("/cockpit-docker")
            row = "#containers-containers tr[data-row-name='0-test-oldname']"
            b.wait_in_text(row, "Exited")

            # renaming is only offered for stopped containers
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Rename')")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_in_text(".pf-v6-c-modal-box", "Rename container test-oldname")
            b.set_input_text("#rename-dialog-container-name", "test-renamed")
            b.click("#btn-rename-dialog-container")
            b.wait_not_present(".pf-v6-c-modal-box")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_visible("#containers-containers tr[data-row-name='0-test-renamed']")
            b.wait_not_present("#containers-containers tr[data-row-name='0-test-oldname']")
        finally:
            m.execute("docker rm -f test-renamed test-oldname")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testContainerForceDelete(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            m.execute("docker run -d --name test-forcedelete busybox sleep 10000")
            b.reload()
            b.enter_page("/cockpit-docker")
            row = "#containers-containers tr[data-row-name='0-test-forcedelete']"
            b.wait_in_text(row, "Running")

            # deleting a running container asks for a force-remove confirmation
            b.click(row + " .pf-v6-c-menu-toggle")
            b.click(".pf-v6-c-menu__item:contains('Delete')")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_in_text(".pf-v6-c-modal-box", "Delete test-forcedelete?")
            b.click(".pf-v6-c-modal-box__footer button:contains('Force delete')")
            b.wait_not_present(".pf-v6-c-modal-box")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present("#containers-containers tr[data-row-name='0-test-forcedelete']")
        finally:
            m.execute("docker rm -f test-forcedelete")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testImageCreateRun(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
            b.wait_visible("#containers-images .image-name")
            b.click("#containers-images .ct-container-create")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_text(".pf-v6-c-modal-box__title", "Create container")

            # create and run the pre-pulled busybox image, with a command that
            # keeps the container running
            b.set_input_text("#run-image-dialog-name", "test-from-image")
            b.set_input_text("#run-image-dialog-command", "sleep 10000")
            b.click("#create-image-create-run-btn")
            b.wait_not_present(".pf-v6-c-modal-box")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_in_text("#containers-containers tr[data-row-name='0-test-from-image']", "Running")
        finally:
            m.execute("docker rm -f test-from-image")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-name")

    def testCreateStackDialog(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/cockpit-docker")
        try:
            # opening the create-stack dialog from the containers toolbar
            b.click("#containers-containers-create-stack-btn")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_text(".pf-v6-c-modal-box__title", "Create stack")
            b.wait_visible("#create-stack-dialog-name")

            # the project name is required and must not contain spaces
            b.set_input_text("#create-stack-dialog-name", "")
            b.wait_in_text(".pf-v6-c-modal-box", "Project name is required.")
            b.set_input_text("#create-stack-dialog-name", "has space")
            b.wait_in_text(".pf-v6-c-modal-box", "Invalid characters")

            # a valid name clears the error and saves the stack files, which
            # show up in the inactive stacks section
            b.set_input_text("#create-stack-dialog-name", "test-ui-stack")
            b.wait_not_in_text(".pf-v6-c-modal-box", "Invalid characters")
            b.click("#create-stack-dialog-create-btn")
            b.wait_not_present(".pf-v6-c-modal-box")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_in_text(".container-inactive-stacks", "test-ui-stack")
            b.wait_visible("tr[data-row-name='test-ui-stack']")
        finally:
            # remove the stack directory created by the dialog
            m.execute("rm -rf /var/lib/cockpit-docker/stacks/test-ui-stack")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-inactive-stacks")

    def testStackLifecycle(self):
        b = self.browser
        m = self.machine

        # create the stack's compose files under the plugin's stack directory
        m.execute('''mkdir -p /var/lib/cockpit-docker/stacks/test-stack
cat > /var/lib/cockpit-docker/stacks/test-stack/docker-compose.yml <<'EOF'
services:
  web:
    image: busybox
    command: ["sleep", "3600"]
EOF''')

        self.login_and_go("/cockpit-docker")
        b.reload()
        b.enter_page("/cockpit-docker")
        try:
            # the not-yet-started stack is listed under inactive stacks
            b.wait_in_text(".container-inactive-stacks", "test-stack")
            b.wait_visible("tr[data-row-name='test-stack']")

            # its edit dialog is prefilled with the stack name
            b.click("#inactive-stack-actions-test-stack")
            b.click(".pf-v6-c-menu__item:contains('Edit')")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_text(".pf-v6-c-modal-box__title", "Edit stack test-stack")
            b.click(".btn-cancel")
            b.wait_not_present(".pf-v6-c-modal-box")

            # starting the stack brings its container into the listing
            b.click("#inactive-stack-start-test-stack")
            b.wait_visible("#table-test-stack")
            b.wait_in_text("#table-test-stack .stack-name", "test-stack")
            b.wait_in_text("#table-test-stack .ct-badge-stack-running", "Running")
            b.wait_visible("#table-test-stack tr[data-row-name='0-test-stack-web-1']")

            # stopping the stack marks it stopped, but keeps its containers
            b.click("#stack-actions-dropdown-test-stack-web-1")
            b.click(".pf-v6-c-menu__item.stack-action-stop")
            b.wait_in_text("#table-test-stack .ct-badge-stack-stopped", "Stopped")
            b.wait_visible("#table-test-stack tr[data-row-name='0-test-stack-web-1']")

            # ... and starting it again returns it to running
            b.click("#stack-actions-dropdown-test-stack-web-1")
            b.click(".pf-v6-c-menu__item.stack-action-start")
            b.wait_in_text("#table-test-stack .ct-badge-stack-running", "Running")

            # removing the stack deletes the containers but keeps the files,
            # so it moves back to the inactive stacks section
            b.click("#stack-actions-dropdown-test-stack-web-1")
            b.click(".pf-v6-c-menu__item.stack-action-remove")
            b.wait_visible(".pf-v6-c-modal-box")
            b.wait_in_text(".pf-v6-c-modal-box", "Remove stack?")
            b.click(".pf-v6-c-modal-box__footer button:contains('Remove')")
            b.wait_not_present(".pf-v6-c-modal-box")
            # the containers are force-deleted, their removal cascades through
            # the event stream; reload for a deterministic listing
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_in_text(".container-inactive-stacks", "test-stack")
        finally:
            # bring down any leftover containers and remove the stack files
            m.execute("cd /var/lib/cockpit-docker/stacks/test-stack && docker compose down --remove-orphans >/dev/null 2>&1 || true")
            m.execute("rm -rf /var/lib/cockpit-docker/stacks/test-stack")
            b.reload()
            b.enter_page("/cockpit-docker")
            b.wait_not_present(".container-inactive-stacks")

    def testImages(self):
        b = self.browser

        self.login_and_go("/cockpit-docker")

        # the image listing is collapsed by default; expand it
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        row = "#containers-images tr[data-row-name='0-busybox:latest']"
        b.wait_visible(row)

        # the pre-pulled busybox image is listed with its metadata
        b.wait_in_text(row, "busybox:latest")
        b.wait_in_text(row, "system")
        b.wait_in_text(row, "unused")
        b.wait_in_text("#containers-images", "1 image total")

        # the listing can be collapsed again
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        b.wait_not_visible("#containers-images .image-name")

    def testImageDetails(self):
        b = self.browser

        self.login_and_go("/cockpit-docker")
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        b.wait_visible("#containers-images .image-name")

        # expand the image row
        b.click("#containers-images tr[data-row-name='0-busybox:latest'] .pf-v6-c-table__toggle button")
        b.wait_visible("#containers-images .pf-v6-c-tabs__list")

        # the Details tab shows the image metadata
        b.wait_in_text("#containers-images .image-details", "busybox:latest")
        b.wait_in_text("#containers-images .image-details", "Command")

        # the History tab shows the image build history
        b.click("#containers-images .pf-v6-c-tabs__item button:contains('History')")
        b.wait_in_text("#containers-images .ct-listing-panel-body .pf-v6-c-table", "Created by")

    def testImageRunDialog(self):
        b = self.browser

        self.login_and_go("/cockpit-docker")
        b.click("#containers-images .pf-v6-c-expandable-section__toggle button")
        b.wait_visible("#containers-images .image-name")

        # opening the run-image dialog from the row action
        b.click("#containers-images .ct-container-create")
        b.wait_visible(".pf-v6-c-modal-box")
        b.wait_text(".pf-v6-c-modal-box__title", "Create container")
        b.wait_visible("#run-image-dialog-name")
        # cancel without creating anything
        b.click(".btn-cancel")
        b.wait_not_present(".pf-v6-c-modal-box")


# This test gets its own fresh VM (not @nondestructive) because it makes
# permanent changes: it hides the docker CLI and stops the docker daemon.
class TestDockerNotInstalled(testlib.MachineCase):
    def testDockerNotInstalled(self):
        b = self.browser
        m = self.machine

        # simulate a system without docker: no daemon and no docker CLI
        m.execute("systemctl mask docker docker.socket")
        m.execute("systemctl stop docker docker.socket")
        m.execute("mv /usr/bin/docker /usr/bin/docker.example")

        self.login_and_go("/cockpit-docker")

        b.wait_in_text(".pf-v6-c-empty-state__title", "Docker is not installed")
        b.wait_in_text(".pf-v6-c-empty-state__body", "Docker is not installed on this system.")
        b.wait_in_text(".pf-v6-c-empty-state__body", "See Docker installation instructions")


if __name__ == '__main__':
    testlib.test_main()
